### ISSUE TITLE
Deal with mounting masses of CSVs

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_get_csv#11]
I was surprised to discover that Arca's disk usage was at 92%, and went hunting around for the cause. It wasn't the `/tmp` directory - turns out that the BCRDH site's `files` directory is crammed full of files, including Collection CSVs from this module.

If such a CSV is generated, it's put in the `files` directory, and therefore never leaves. It's invisible to Drupal, as far as I can tell, and there's no automatic deletion of them.

Possible options that come to my mind:

1. Put the files in `/tmp` - but I suspect you then couldn't create a download link for them, is that right?
2. Include some sort of Drupal Cron entry that clears out these files once a day
3. Include an admin page that lists all the CSVs generated and their collections, with checkboxes to delete them (could be combined with option 2)

What do you think?

**Comment by mjordan** [comment]
I think option 2, with a config option for how long to keep them, is the way to go. We'd need to build in a way for the module to know which files to delete.

**Comment by bondjimbond** [comment]
I guess it would have to record the filenames in an array when the files are generated, which can be referred to for the list. Should be pretty straightforward, I think?

**Comment by mjordan** [comment]
Or, we can create a configurable subdir and put all the csvs in it. The cronjob would only check age of files in it. This would also make accidentally finding the files via the web harder.

**Comment by bondjimbond** [comment]
That's good. So it'd be at `/var/www/html/sites/mysite/files/collection_csv` or whatever?

**Comment by bondjimbond** [comment]
Certainly better than dumping it all into `files`.

**Comment by mjordan** [comment]
Yes, but the directory name should be an admin option. I think I've done this elsewhere - want me to take crack at it?

**Comment by bondjimbond** [comment]
Please do!

**Comment by mjordan** [comment]
@bondjimbond can you test the issue-11 branch? Two new admin settings at `admin/islandora/tools/islandora_get_csv` for the name of the subdirectory where the CSV files are written and for the number of hours to keep them before cron wipes them.

**Comment by bondjimbond** [comment]
Thanks! I've checked out the branch and set cron to delete in one hour; we'll see how it goes! The new file was put into the configured subdirectory, so that's a good start.
