### ISSUE TITLE
Drush option to include "all child objects"

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_get_csv#17]
There is a checkbox to "Include all child objects, including pages, child items, and members of subcollections" on the Collection management panel. But there is no such option for Drush.

Drush would be ideal for getting a complete representation of the repository in CSV (see #14) since you can avoid timeouts.

**Comment by mjordan** [comment]
I'm sorry I can't come up with a graceful way of adding this option to the drush command, but if you want to modify your module's code, you can enable this by adding `$options['islandora_get_csv_include_descendents'] = true;` at https://github.com/mjordan/islandora_get_csv/blob/master/includes/utilities.inc#L77

```php
// Ancestors use the literal PID, not the one prepended by 'info:fedora'.
$options['islandora_get_csv_include_descendents'] = true; // <-- add this
  if ($collection_limiter == 'ancestors' && $options['islandora_get_csv_include_descendents']) {
    // $fq = 'ancestors_ms:"' . $pid . '"';
    $collection_filter = 'ancestors_ms:%22' . $pid . '%22';
  }
```

If you do that, all children should be included.

**Comment by bondjimbond** [comment]
Ah, nice, thanks! I have been playing a bit with the code, but was having trouble with sorting out where to put it. I'll think on whether I can find a good way to make this a Drush option too.

**Comment by mjordan** [comment]
Yeah, I looked at it last night an my eyes glazed over (possibly due to the hackish way I created the form, possibly due to fever).

**Comment by bondjimbond** [comment]
Adding that line definitely did the trick -- some collection, first CSV = 23 kb, second CSV = 5 MB.

I'll see about the drush thing when I have some time to play with it. Thanks again!

**Comment by mjordan** [comment]
Merged - thanks, this an excellent improvement!
