### ISSUE TITLE
Testing Islandora Metadata CSV module, get nothing in return

### ISSUE THREAD

**Issue by simonhm** [mjordan/islandora_get_csv#4]
When clicking on the "Generate metadata CSV" button, we got nothing (even no errors, no warning, ...) in return. The "Download your CSV at here" link is not showed up. 
We're using the default settings in admin/islandora/tools/islandora_get_csv 
and using public file system.
Simon.

**Comment by simonhm** [comment]
No errors in log file of Apache as well.

**Comment by mjordan** [comment]
And you can confirm that the CSV file is not being written to your public files directory?

**Comment by simonhm** [comment]
I've just added some more code here:
![image](https://user-images.githubusercontent.com/6493383/75272440-85029680-57c3-11ea-92ea-4752eca2654d.png)

And here is what returns after clicking on generate button:

![image](https://user-images.githubusercontent.com/6493383/75272500-a6fc1900-57c3-11ea-82a1-cc3b239d9e3f.png)

Simon.

**Comment by simonhm** [comment]
Yes, I've checked in public dir /files, there are no .csv files created there.
Simon.

**Comment by mjordan** [comment]
Can you see what's going on at https://github.com/mjordan/islandora_get_csv/blob/master/islandora_get_csv.module#L146 ?

**Comment by simonhm** [comment]
Adding code there:

  module_load_include('inc', 'islandora_get_csv', 'includes/utilities');
  if (!$metadata_csv = islandora_get_csv_query_solr($pid, $collection_limiter)) {
    drupal_set_message(t("No records found."));
    return FALSE;
  }

I get: 
"No record found" after clicking button.

It seems like I'm getting nothing in return from SOLR query.

**Comment by mjordan** [comment]
Hm.. can you try adjusting the admin settings (set "Solr field pattern" to *, leave "Solr fields to exclude" empty, uncheck "Remove single-value fields where applicable "?

**Comment by simonhm** [comment]
Aha, I think I know what's going on now.
I added the code here:

![image](https://user-images.githubusercontent.com/6493383/75274120-dd3b9780-57c7-11ea-9428-45f79f767f93.png)

and here is the request link from your module: http://http://our_SOLR_endpoint_domain:8080/solr/select?q=*:*&wt=csv&rows=0&fl=mods_*

![image](https://user-images.githubusercontent.com/6493383/75275813-b16de100-57ca-11ea-9822-1b62d334d6c0.png)

I think you must get rid of "http://" incase the SOLR endpoint got "http://" in there already.

Simon.

**Comment by mjordan** [comment]
Good catch. That shouldn't be hard coded. I'll fix that this evening.

In the meantime, can you replace 'http://' with 'https://' and to confirm that is the only problem?

**Comment by simonhm** [comment]
Fixed the "https://", but still:
No records found.
No CSV file is created.
Seems like still having some problem with SOLR query.
When I try to open the SOLR_request URL from browser, I got error:
"This site can’t be reached 10.xxx.yyy.178 (IP of our SOLR server) took too long to respond."

Any wrong here ?

Simon.

**Comment by simonhm** [comment]
The test request link:  https://10.xxx.yyy.178:8080/solr/select?q=*:*&wt=csv&rows=0&fl=mods_*
10.xxx.yyy.178  is our SOLR server address.

**Comment by simonhm** [comment]
Replaced the IP address in SOLR URL by domain >> The test request link is working now by opening directly on browser.

![image](https://user-images.githubusercontent.com/6493383/75277929-8f765d80-57ce-11ea-9b5f-8046959b3e23.png)

Tried adjusting the admin settings (set "Solr field pattern" to *, leave "Solr fields to exclude" empty, uncheck "Remove single-value fields where applicable " as you suggested, but still ... nothing in return:

![image](https://user-images.githubusercontent.com/6493383/75277707-255db880-57ce-11ea-938b-9b768a89e861.png)

Hmmh ...

**Comment by simonhm** [comment]
The final "solr request" (the one returns metadata CSV) got problem:

![image](https://user-images.githubusercontent.com/6493383/75279104-a61db400-57d0-11ea-9701-8320231ba1b1.png)

Something wrong here !

**Comment by simonhm** [comment]
There are some possible errors I've just found:

1. In our SOLR, we don't have: RELS_EXT_isMemberOfCollection_uri_t field.
We have: RELS_EXT_isMemberOfCollection_uri_mt and RELS_EXT_isMemberOfCollection_uri_ms

To make the module "may" work for us, I need to change these lines 80 and 81:
https://github.com/mjordan/islandora_get_csv/blob/984775a2344392aa86a6970ecca914f50fc1f30c/includes/utilities.inc#L80
RELS_EXT_isMemberOfCollection_uri_t  into RELS_EXT_isMemberOfCollection_uri_mt 

2. Got 400 Bad Request error from file_get_contents:
![image](https://user-images.githubusercontent.com/6493383/75282667-0d3e6700-57d7-11ea-95c7-2bce02e3cabe.png)

Something wrong with special chars in the URL request, I think.
For example:
- Remove \ in fq=RELS_EXT_isMemberOfCollection_uri_mt:"info\:fedora/OurRepository\:learning_objects_dev"
I will get results by opening directly the request URL on browser. But still get 400 Bad Request from the code (from file_get_contents)

- Remove fq=RELS_EXT_isMemberOfCollection_uri_mt:"info\:fedora/OurRepository\:learning_objects_dev" from URL request in the code, I will get the download CSV file link. But I get all of objects instead of only members of the collection, since I don't keep the fq filter in the request.

Still digging why those fq filters are causing 400 Bad Request for file_get_contents.

**Comment by simonhm** [comment]
OK, I made module work for me.
I had to change the code at line #81:

https://github.com/mjordan/islandora_get_csv/blob/984775a2344392aa86a6970ecca914f50fc1f30c/includes/utilities.inc#L81

from: 
`$collection_filter = 'RELS_EXT_isMemberOfCollection_uri_t:"info\:fedora/' . $collection_pid . '"';`
to: 
 `$collection_filter = urlencode('RELS_EXT_isMemberOfCollection_uri_mt:"info\:fedora/' . $collection_pid . '"');`

and voila, it's working now !

![image](https://user-images.githubusercontent.com/6493383/75286000-4bd72000-57dd-11ea-855e-427075aa5a57.png)

Simon.

**Comment by mjordan** [comment]
@simonhm I've opened (and resolved) #5 and #6 to address the problems you found. Now, there are two new admin settings:

![get_csv](https://user-images.githubusercontent.com/403918/75309472-fd8a4700-5805-11ea-8c63-eb6524a700c5.PNG)

Please pull in the latest changes to the `master` branch and test and let me know how it goes.

**Comment by simonhm** [comment]
Hi Mark,
I've just pulled the latest change. It almost works for me, except the 400 Bad Request error from file_get_contents that hasn't been fixed. 
I don't know why it seems working for you without the below fix, but in our server (maybe we got some tricky settings) I need to do once more change to make your module work for us.

At line 83, insert function "urlencode" to encode your $collection_filter string before using it in a query request.
https://github.com/mjordan/islandora_get_csv/blob/75ab3e6efd4acdb2f1087693185a4dfed4c268e6/includes/utilities.inc#L83

The fixed code should be:  `$collection_filter = urlencode($collection_field . ':"info\:fedora/' . $collection_pid . '"');`

Simon.

**Comment by mjordan** [comment]
@simonhm I will test that change to make sure it doesn't break the module on the systems I have been testing on, but I won't be able to look at this until the weekend.

**Comment by simonhm** [comment]
Great ! Anyway we found out why and how to make the module work for us. Our customers should be very happy to use this module. It's quite convenient for them to download their CSV metadata files by themselves without technical skills. Thank you very much, Mark !

**Comment by mjordan** [comment]
Thank you for testing and helping it work for more people.

**Comment by mjordan** [comment]
`urlencode` added. I think that's it. Thank you very much for testing.
