### ISSUE TITLE
CSV download link not appearing

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_get_csv#7]
The "generate CSV" button refreshes the page, yet does not provide a CSV link to download.

Nothing in the Drupal log seems to indicate the source of the problem.

**Comment by bondjimbond** [comment]
Edit: It's not XACML restrictions, as I have just tested this in a collection without XACML restrictions.

This module is working fine in Vagrant, but not in my production environment. Any advice on how to troubleshoot this and find the source of the conflict?

**Comment by mjordan** [comment]
Try to log (via `drupal_debug()` for example) the `$solr_request` value at https://github.com/mjordan/islandora_get_csv/blob/master/includes/utilities.inc#L99 to see what's missing from the Solr query.

**Comment by mjordan** [comment]
Is it just that the menu link is not appearing in your production, or is it more than that? My advice in the last comment assumes that the link is appearing....

**Comment by bondjimbond** [comment]
In Vagrant, the message "Download your CSV at here" appears (drupal_set_message probably) after you click Generate CSV. In production, everything else is present except the download message.

**Comment by bondjimbond** [comment]
> Try to log (via drupal_debug() for example) the $solr_request value

Is that the same as checking off the Solr checkbox? I do see that the value it shows is a bit weird -- it's got `http://` twice.

`http://http://arca-be.is.sfu.ca:8080/solr/collection1/select?q=PID:*&wt=csv&rows=1000000&fq=RELS_EXT_isMemberOfCollection_uri_s%3A%22info%5C%3Afedora%2Fbchdp%5C%3Abackgrounds%22&fl=PID,RELS_EXT_hasModel_uri_s`

**Comment by bondjimbond** [comment]
If I edit https://github.com/mjordan/islandora_get_csv/blob/master/includes/utilities.inc#L99 and remove `$protocol` from the string, my CSV link appears.

Can you maybe introduce a check to determine whether `$solr_endpoint` already contains the protocol in it before deciding to add the protocol variable?

**Comment by mjordan** [comment]
It's already there, can you check the module's admin setttings?

**Comment by bondjimbond** [comment]
Yeah, now that I'm there I see there's a Protocol option which you can set to "none". Wasn't expecting that.

**Comment by mjordan** [comment]
Problem is that protocol is optional in Solr Search, and this module uses its Solr URL setting.

**Comment by bondjimbond** [comment]
Might it be possible to screen it? e.g. look for "http" at the beginning of the `$solr_endpoint` string, and if it is present, flash a warning: "Your Solr endpoint already contains the protocol. Please select "none" under Protocol at the configuration page."
